<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFODyy2S\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFODyy2S/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFODyy2S.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFODyy2S\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFODyy2S\App_KernelDevDebugContainer([
    'container.build_hash' => 'FODyy2S',
    'container.build_id' => '01a7a6f3',
    'container.build_time' => 1740003336,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFODyy2S');
